<?php
return [
    'table_module'=>[
        'dashboard',
        'category',
        'banner',
        'brand',
        'background',
        'menu',
        'role',
        'user',
        'customer',
        'product',
        'contact',
        'blog',
        'order',
        'permission',
    ]
];
